/* Generated by scripts/make_sw.py from the production bundle — do not
 * edit. KPuzzle kpuzzle-3ea87be: precache-first, so the app runs offline after
 * the first visit. */
'use strict';

const CACHE = 'kpuzzle-kpuzzle-3ea87be';
const PRECACHE = [
  ".git/HEAD",
  ".git/config",
  ".git/description",
  ".git/hooks/applypatch-msg.sample",
  ".git/hooks/commit-msg.sample",
  ".git/hooks/fsmonitor-watchman.sample",
  ".git/hooks/post-update.sample",
  ".git/hooks/pre-applypatch.sample",
  ".git/hooks/pre-commit.sample",
  ".git/hooks/pre-merge-commit.sample",
  ".git/hooks/pre-push.sample",
  ".git/hooks/pre-rebase.sample",
  ".git/hooks/pre-receive.sample",
  ".git/hooks/prepare-commit-msg.sample",
  ".git/hooks/push-to-checkout.sample",
  ".git/hooks/sendemail-validate.sample",
  ".git/hooks/update.sample",
  ".git/index",
  ".git/info/exclude",
  ".git/logs/HEAD",
  ".git/logs/refs/heads/main",
  ".git/objects/pack/pack-16155e43f02e0ac509014c0aa3de328139c85f98.idx",
  ".git/objects/pack/pack-16155e43f02e0ac509014c0aa3de328139c85f98.pack",
  ".git/objects/pack/pack-16155e43f02e0ac509014c0aa3de328139c85f98.rev",
  ".git/packed-refs",
  ".git/refs/heads/main",
  ".git/shallow",
  "apple-touch-icon.png",
  "bfa5198fb2fe683c613a.wasm",
  "cda0dca6ff64ebef7a6c.wasm",
  "composeResources/ru.kanphis.puzzle/drawable/add.xml",
  "composeResources/ru.kanphis.puzzle/drawable/akari.xml",
  "composeResources/ru.kanphis.puzzle/drawable/arrow_back.xml",
  "composeResources/ru.kanphis.puzzle/drawable/book.xml",
  "composeResources/ru.kanphis.puzzle/drawable/bookmark.xml",
  "composeResources/ru.kanphis.puzzle/drawable/check.xml",
  "composeResources/ru.kanphis.puzzle/drawable/delete.xml",
  "composeResources/ru.kanphis.puzzle/drawable/edit.xml",
  "composeResources/ru.kanphis.puzzle/drawable/event_40.xml",
  "composeResources/ru.kanphis.puzzle/drawable/flag.xml",
  "composeResources/ru.kanphis.puzzle/drawable/grid_view.xml",
  "composeResources/ru.kanphis.puzzle/drawable/hashiwokakero.xml",
  "composeResources/ru.kanphis.puzzle/drawable/history.xml",
  "composeResources/ru.kanphis.puzzle/drawable/hitori.xml",
  "composeResources/ru.kanphis.puzzle/drawable/image.xml",
  "composeResources/ru.kanphis.puzzle/drawable/info.xml",
  "composeResources/ru.kanphis.puzzle/drawable/kakuro.xml",
  "composeResources/ru.kanphis.puzzle/drawable/keyboard_arrow_down.xml",
  "composeResources/ru.kanphis.puzzle/drawable/keyboard_arrow_left.xml",
  "composeResources/ru.kanphis.puzzle/drawable/keyboard_arrow_right.xml",
  "composeResources/ru.kanphis.puzzle/drawable/leaderboard.xml",
  "composeResources/ru.kanphis.puzzle/drawable/lightbulb.xml",
  "composeResources/ru.kanphis.puzzle/drawable/local_fire_department.xml",
  "composeResources/ru.kanphis.puzzle/drawable/masyu.xml",
  "composeResources/ru.kanphis.puzzle/drawable/minesweeper.xml",
  "composeResources/ru.kanphis.puzzle/drawable/more_vert.xml",
  "composeResources/ru.kanphis.puzzle/drawable/nonograms.xml",
  "composeResources/ru.kanphis.puzzle/drawable/nurikabe.xml",
  "composeResources/ru.kanphis.puzzle/drawable/redo.xml",
  "composeResources/ru.kanphis.puzzle/drawable/remove.xml",
  "composeResources/ru.kanphis.puzzle/drawable/restart_alt.xml",
  "composeResources/ru.kanphis.puzzle/drawable/settings.xml",
  "composeResources/ru.kanphis.puzzle/drawable/shikaku.xml",
  "composeResources/ru.kanphis.puzzle/drawable/slitherlink.xml",
  "composeResources/ru.kanphis.puzzle/drawable/sudoku.xml",
  "composeResources/ru.kanphis.puzzle/drawable/suguru.xml",
  "composeResources/ru.kanphis.puzzle/drawable/undo.xml",
  "composeResources/ru.kanphis.puzzle/files/inter_ofl.txt",
  "composeResources/ru.kanphis.puzzle/font/inter_variable.ttf",
  "composeResources/ru.kanphis.puzzle/values/strings.commonMain.cvr",
  "composeResources/ru.kanphis.puzzle/values-ru/strings.commonMain.cvr",
  "composeResources/ru.kanphis.puzzle.shared/files/aboutlibraries.json",
  "favicon-32.png",
  "favicon.svg",
  "icon-192.png",
  "icon-512.png",
  "icon-maskable-512.png",
  "index.html",
  "manifest.webmanifest",
  "og-image.png",
  "privacy.html",
  "webApp.js"
];

self.addEventListener('install', (event) => {
  event.waitUntil((async () => {
    const cache = await caches.open(CACHE);
    await cache.addAll(PRECACHE);
    await self.skipWaiting();
  })());
});

self.addEventListener('activate', (event) => {
  event.waitUntil((async () => {
    const keys = await caches.keys();
    await Promise.all(keys.filter((key) => key !== CACHE)
        .map((key) => caches.delete(key)));
    await self.clients.claim();
  })());
});

self.addEventListener('fetch', (event) => {
  const request = event.request;
  if (request.method !== 'GET') return;
  const url = new URL(request.url);
  if (url.origin !== self.location.origin) return;
  event.respondWith((async () => {
    const cache = await caches.open(CACHE);
    const cached = await cache.match(request, {ignoreSearch: true});
    if (cached) return cached;
    try {
      const response = await fetch(request);
      if (response.ok && response.type === 'basic') {
        cache.put(request, response.clone());
      }
      return response;
    } catch (err) {
      // Offline and not precached: navigations fall back to the shell.
      if (request.mode === 'navigate') {
        const shell = await cache.match('./', {ignoreSearch: true});
        if (shell) return shell;
      }
      throw err;
    }
  })());
});
